import Head from "next/head";
import Blog from "./components/Blog";

export default function Home() {
  return (
    <div>
      <Head>
        <title>The Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/pro.ico" />
      </Head>
      <Blog />
    </div>
  );
}
